config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'

  get 'assets/images'

  get 'dashboards/index'

  get 'recipes/index'

  get 'recipes/show'

  devise_for :users
  resources :pantries

  resources :recipes

  #root 'pantries#index'

  #post '/forms/results', :to => 'forms#results'

  #get 'forms/new', :to => 'forms#new'

  #get 'forms/create'

  #get 'forms/edit'

  #get 'forms/update'

  #get 'forms/show'

  #get 'forms/destroy'

  #root 'pantries#new'

  post '/pantries/results', :to => 'pantries#results'

  get 'pantries/new', :to => 'pantries#new'

  # get 'pantries/create'

  # get 'pantries/edit'

  # get 'pantries/update'

  # get 'pantries/show'

  # get 'pantries/destroy'


  # # Example of regular route:
  # #   get 'products/:id' => 'catalog#view'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :ingredient

  def self.category_name(ingr_id) # for ingredient.category_id
    result = ""
    if ingr_id == 1
      result = "grains"
    elsif ingr_id == 2
      result = "fruits"
    elsif ingr_id == 3
      result = "vegetables"
    elsif ingr_id == 4
      result = "meats"
    elsif ingr_id == 5
      result = "dairy"
    else ingr_id == 6
      result = "fats"
    end
    return result
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :category
  has_many :ingredient_recipes
  has_many :recipes, :through => :ingredient_recipes
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, :through => :ingredient_recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # layout :layout_by_resource

  # protected

  # def layout_by_resource
  #   if devise_controller?
  #     "layout_name_for_devise"
  #   else
  #     "application"
  #   end
  # end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if user_signed_in?
      redirect_to pantries_path
    end
  end
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController

  def index
    @categories = Category.all
    @ingredients = Ingredient.all
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    params[:pantry].delete_if {|k, v| v.empty?}
    @ingredients = IngredientsRecipe.where(ingredient_id: params[:pantry].values).includes(:recipe) #.values gets array of values isntead of hash
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/user_auth_controller.rb
class UserAuthController < ApplicationController
  # In this first case, suppose we want to ensure that every controller action requires a logged in user, except for the login and register actions:
  skip_before_action :authenticate_user!

  def login
    '...'
  end

  def register
    '...'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  # user_signed_in?
  # current_user
  # user_sessions
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/helpers/pantry_helper.rb
module PantryHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_auth_helper.rb
module UserAuthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<main class="homepage">
    <div class="jumbotron" style="padding-top: 14%;
    padding-bottom: 14%;">
        <h1 class="logo">Pantry.io</h1>

        <div class="hp-bn">
            <button type="button" class="btn btn-secondary homepage-bn"><%= link_to "Login", new_user_session_path %></button>
            <button type="button" class="btn btn-secondary homepage-bn"><%= link_to "Sign up", new_user_registration_path %></button>
        </div>
    </div>

    <div class="about">
        <h3>About Us</h3>
        <p>Pantry.io helps you find dishes that you can make with whatever ingredients you may have in your pantry, fridge, or kitchen.</p>
    </div>

    <div class="about">
        <h3>How it works</h3>
        <p>Pantry.io is very easy to use. All you have to do is sign up. Once you log in, select a category from the drop down menu and you will see a list of ingredients. Choose the ingredients you want and submit them to the cart. All your ingredients will be shown in the cart. You may go ahead and choose other ingredients from another category and submit those. Once your cart is ready, submit it--a list of recipes with your ingredients in them will appear.</p>

    </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pantry.io</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pantries/create.html.erb
<h1>Forms#create</h1>
<p>Find me in app/views/forms/create.html.erb</p>

app/views/pantries/destroy.html.erb
<h1>Forms#destroy</h1>
<p>Find me in app/views/forms/destroy.html.erb</p>

app/views/pantries/edit.html.erb
<h1>Forms#edit</h1>
<p>Find me in app/views/forms/edit.html.erb</p>

app/views/pantries/index.html.erb
<div class="app-logo">
  <%= image_tag 'chef.png' %>
  <h1 class="app">Pantry.io</h1>
</div>

<div class="row">
  <div id="ingredients" class="section col-lg-offset-2 col-md-offset-2 col-lg-4 col-md-4 col-sm-12 col-xs-12">
    <select id="dropdown" width="300px" class="categories" name="Categories">
      <option value="choose">Choose a Food Type</option>
        <% @categories.each do |category| %>
          <option class="ingredient" value="<%= category.name.downcase %>"><%= category.name %></option>
        <% end %>
    </select>

    <p class="choose">Ingredients:</p>

  <% i = 0 %>
  <% @ingredients.each do |ingredient| %>
  <input id="cbox<%=i+=1%>" class="cbox <%= Category.category_name(ingredient.category_id) %>" type="checkbox" value="<%= ingredient.id %>">
  <label for="cbox<%=i%>" id="label<%=i%>" class="cbox <%= Category.category_name(ingredient.category_id) %>"><%= ingredient.name %></label>
  <% end %>

    <button id="ingredients_to_cart" type="submit" class="btn btn-primary">Select</button>
  </div>

  <div id="pantry" class="section col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <p class="choose">Pantry: </p>

      <div id="cart_item1"></div>
      <div id="cart_item2"></div>
      <div id="cart_item3"></div>
      <div id="cart_item4"></div>
      <div id="cart_item5"></div>
      <div id="cart_item6"></div>
      <div id="cart_item7"></div>
      <div id="cart_item8"></div>
      <div id="cart_item9"></div>
      <div id="cart_item10"></div>
      <div id="cart_item11"></div>
      <div id="cart_item12"></div>
      <div id="cart_item13"></div>
      <div id="cart_item14"></div>
      <div id="cart_item15"></div>
      <div id="cart_item16"></div>
      <div id="cart_item17"></div>
      <div id="cart_item18"></div>
      <div id="cart_item19"></div>
      <div id="cart_item20"></div>
      <div id="cart_item21"></div>
      <div id="cart_item22"></div>
      <div id="cart_item23"></div>
      <div id="cart_item24"></div>

    <%= form_for :pantry, method: "get", url: recipes_path do |f| %>
      <%= f.text_field :item1, hidden: true %>
      <%= f.text_field :item2, hidden: true %>
      <%= f.text_field :item3, hidden: true %>
      <%= f.text_field :item4, hidden: true %>
      <%= f.text_field :item5, hidden: true %>
      <%= f.text_field :item6, hidden: true %>
      <%= f.text_field :item7, hidden: true %>
      <%= f.text_field :item8, hidden: true %>
      <%= f.text_field :item9, hidden: true %>
      <%= f.text_field :item10, hidden: true %>
      <%= f.text_field :item11, hidden: true %>
      <%= f.text_field :item12, hidden: true %>
      <%= f.text_field :item13, hidden: true %>
      <%= f.text_field :item14, hidden: true %>
      <%= f.text_field :item15, hidden: true %>
      <%= f.text_field :item16, hidden: true %>
      <%= f.text_field :item17, hidden: true %>
      <%= f.text_field :item18, hidden: true %>
      <%= f.text_field :item19, hidden: true %>
      <%= f.text_field :item20, hidden: true %>
      <%= f.text_field :item21, hidden: true %>
      <%= f.text_field :item22, hidden: true %>
      <%= f.text_field :item23, hidden: true %>
      <%= f.text_field :item24, hidden: true %>
      <%= f.submit value: "Get Recipes", :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/pantries/new.html.erb
<h1>Forms#new</h1>
<p>Find me in app/views/forms/new.html.erb</p>

<select>

<% @categories.each do |category| %>
	<option value="<%= category.id %>"><%= category.name %></option>
<% end %>

</select>


<!-- form from joe/andrew -->

<form action="/recipes">
<% @categories.each do |category| %>
  <h3><%= category.name %></h3>
  <% category.ingredients.each do |ingredient| %>
    <input type="checkbox" name="ingredients[]" value="<%= ingredient.id %>"><%= ingredient.name %>
  <% end %>

<% end %>

<input type="submit" value="SUBMIT">
</form>

app/views/pantries/show.html.erb
<h1>Forms#show</h1>
<p>Find me in app/views/forms/show.html.erb</p>

app/views/pantries/update.html.erb
<h1>Forms#update</h1>
<p>Find me in app/views/forms/update.html.erb</p>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

<%= params %>
<% params.each do |item| %>
<%= item %>
<% end %>


<% @recipes.each do |item| %>
<%= item.title %>
<% end %>

app/views/recipes/index.html.erb
<h1 id="matches" class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">Matches:</h1>


<% @ingredients.each do |item| %>
<br>
<br>
<img style="width: 50%; height: 50%; border-radius: 25px; margin-top: 1%; margin-left: 23%;" src="/assets/<%= item.recipe.img_name %>.jpg" alt="">
<p style="text-align: center;"><%= item.recipe.title %></p>
<p id="description"><%= item.recipe.instructions %></p>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>